### ISSUE TITLE
Can't override build script to use existing libtcod

### ISSUE THREAD

**Issue by ThibaultLemaire** [tomassedovic/tcod-rs#299]
I've tried to use the libtcod provided by my distro,

``` Cargo.toml
[target.x86_64-unknown-linux-gnu.tcod]
rustc-flags = "-L $LIBTCOD -l tcod"
```

but unfortunately cargo gives me the following warning

```
warning: unused manifest key: target.x86_64-unknown-linux-gnu.tcod
```

and compilation fails when pkg-config is not found.

**Comment by tomassedovic** [comment]
Judging by the warning, it looks like you put it in `Cargo.toml`. The overrides should go to `.cargo/config` instead.

I'm not able to actually test any of this now, but FWIW when I was playing with local overrides in a different project, I used these options instead of `rustc-flags`:

```toml
[target.x86_64-unknown-linux-gnu.SDL2]
rustc-link-search = ["lib/x86_64-linux-gnu"]
rustc-link-lib = ["SDL2"]
```
(and I had a `lib/x86_64-linux-gnu/` directory in the root of my repo with all the `so` files)

So try something like this:

```toml
[target.x86_64-unknown-linux-gnu.tcod]
rustc-link-search = ["/usr/lib/tcod"]
rustc-link-lib = ["tcod"]
```

Putting in the absolute path to the directory where the `libtcod.so*` files are. I'm not sure what the path resolution rules are so I'd start with absolute ones and once that works switch over to whatever you actually want.
