### ISSUE TITLE
Upload package to crates.io

### ISSUE THREAD

**Issue by jgilchrist** [tomassedovic/tcod-rs#63]
Is it worth uploading an initial release to crates.io?

This would enable people to put the following in their Cargo.toml file and have everything work automatically:

```toml
[dependencies]
tcod = "*"
```
